name: flutter_move_task_back_example
description: Demonstrates how to use the move_task_to_back plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_move_task_back:
    path: ../

flutter:
  uses-material-design: true
